### ISSUE TITLE
Глава «Велосипеды или расширение возможностей Less» 

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/less-guidebook-for-beginners#14]
В этой главе я предложу читателям ознакомиться с функционалом, который можно построить на основе полученных ими знаний в ходе чтения книги. На самом деле речь пойдёт о том, как имплементировать в мир Less основные функции Sass.

Хотя эта глава пока под вопросом, ибо кому интересно имплементировать что-либо, когда у тебя есть библиотека [homeless](https://github.com/pixelass/homeless).

Текущий приблизительный план:
- Цикл `for`
- Цикл `each`
- Условный оператор `if`

**Comment by mrmlnc** [comment]
Я думаю, что эта глава не должна быть в книге.

Дело в том, что по итогам главы читатель получит ужасный для восприятия синтаксис конструкций, который выбивается из привычного для Less.

```less
.for(3, {.callback(@i) {
  .for(3, {.callback(@j) {
    .item-@{i}-@{j} {
      i: @i;
      j: @j;
    }
  }});
}});
```

Также, если читатель начнёт бездумно применять это на практике, то ничего хорошего не будет.
